name: Turbine; Deploy to DStack

on:
  workflow_call:
    inputs:
      runs_on:
        required: false
        type: string
        default: ubuntu-24.04
        description: Runner tag for workflow
      timeout_minutes:
        required: false
        type: number
        default: 30
        description: Timeout for workflow
      rust_log:
        required: true
        type: string
        description: Rust log level
      turbine_config_file:
        required: true
        type: string
        description: Path to the config file
      cvm_name:
        required: true
        type: string
        description: CVM name
      image_tag:
        required: true
        type: string
        description: Image tag for docker artifact
      aws_secret:
        required: true
        type: string
        description: AWS Secret Manager secret name
      domain:
        required: true
        type: string
        description: Public domain for service
    secrets:
      aws_region:
        required: true
      role_to_assume:
        required: true
      domain_owner:
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ${{ inputs.runs_on }}
    timeout-minutes: ${{ inputs.timeout_minutes }}
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Assume role
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722
        with:
          role-to-assume: ${{ secrets.role_to_assume }}
          audience: sts.amazonaws.com
          aws-region: ${{ secrets.aws_region }}

      - name: Get secrets from AWS Secrets Manager
        id: secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@5e19ff380d035695bdd56bbad320ca535c9063f2
        with:
          secret-ids: |
            ,arn:aws:secretsmanager:${{ secrets.aws_region }}:${{ secrets.domain_owner }}:secret:${{ inputs.aws_secret }}
          parse-json-secrets: true

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: 18

      - name: Install Phala Cloud CLI
        run: |
          curl -fsSL https://bun.sh/install | bash
          export BUN_INSTALL="$HOME/.bun"
          export PATH="$BUN_INSTALL/bin:$PATH"
          npm install -g phala@1.1.1
          phala auth login ${{ env.PHALA_API_KEY }}
          phala auth status

      - name: Create or Upgrade Phala CVMs
        run: |
          export BUN_INSTALL="$HOME/.bun"
          export PATH="$BUN_INSTALL/bin:$PATH"
          echo DSTACK_AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID > .env
          echo DSTACK_AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY >> .env
          echo DSTACK_AWS_REGION=${{ secrets.aws_region }} >> .env
          echo DSTACK_AWS_ECR_REGISTRY=120569639765.dkr.ecr.eu-central-1.amazonaws.com >> .env
          echo SUBMIT_PROVIDER_RPC_URL="${{ env.SUBMIT_PROVIDER_RPC_URL }}" >> .env
          echo READ_PROVIDER_RPC_URL="${{ env.READ_PROVIDER_RPC_URL }}" >> .env
          echo READ_PROVIDER_WS_RPC_URL="${{ env.READ_PROVIDER_WS_RPC_URL }}" >> .env
          echo TURBINE_SIGNER_PKEY=${{ env.TURBINE_SIGNER_PKEY }} >> .env
          echo TURBINE_CONFIG_FILE=${{ inputs.turbine_config_file }} >> .env
          echo TYCHO_AUTH_KEY=${{ env.TYCHO_AUTH_KEY }} >> .env
          echo CLOUDFLARE_API_TOKEN=${{ env.CLOUDFLARE_API_TOKEN }} >> .env
          echo DOMAIN=${{ inputs.domain }} >> .env
          echo RUST_LOG=${{ inputs.rust_log }} >> .env
          echo DOCKER_IMAGE_TAG=${{ inputs.image_tag }} >> .env
          if phala cvms get ${{ inputs.cvm_name }}; then
            echo "CVM is found. Upgrading..."
            phala deploy --debug -n ${{ inputs.cvm_name }} -c ./docker-compose-dstack-prod-tmp.yaml -e .env --private-key ${{ env.DEPLOYER_PRIVATE_KEY }} --kms-id kms-eth-prod9 --instance-type tdx.small --cvm-id ${{ inputs.cvm_name }}
          else
            echo "CVM is not found. Creating..."
            phala deploy --debug -n ${{ inputs.cvm_name }} -c ./docker-compose-dstack-prod-tmp.yaml -e .env --private-key ${{ env.DEPLOYER_PRIVATE_KEY }} --kms-id kms-eth-prod9 --instance-type tdx.small
          fi
