name: Deploy to STG|PROD env

on:
  workflow_call:
    # This makes the workflow reusable
    inputs:
      image_name:
        description: "Application name"
        required: true
        type: string
      image_tag:
        description: "Application tag"
        required: true
        type: string
      environment:
        description: "Environment deploy to"
        required: true
        type: string
    secrets:
      app_id:
        required: true
      app_private_key:
        required: true

jobs:
  promote-to-deploy:
    name: Deploy to STG|PROD env
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate-token
        uses: getsentry/action-github-app-token@v2
        with:
          app_id: ${{ secrets.app_id }}
          private_key: ${{ secrets.app_private_key }}

      - name: Install yq
        run: sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq

      - name: Checkout helm-configuration repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: propeller-heads/helm-configuration
          ref: main
          token: ${{ steps.generate-token.outputs.token }}

      - name: Replace release version
        run: |
          yq eval '.${{ inputs.image_name }}.tag="${{ inputs.image_tag }}"' -i helmwave/${{ inputs.environment }}/versions.yml
          cat helmwave/${{ inputs.environment }}/versions.yml

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ steps.generate-token.outputs.token }}
          message: "${{ inputs.environment }}: Update version of ${{ inputs.image_name }} with tag ${{ inputs.image_tag }}"
          repository: propeller-heads/helm-configuration
